from dataclasses import dataclass

from config_loader import (
    config,
)


@dataclass(frozen=True)
class AppSettings:

    CHAT_ENDPOINT: str

    USE_SERVICE_AS_BRAIN: bool

    SERVICE_API_BASE: str
    SERVICE_MODEL_UID: str
    SERVICE_CONTEXT_WINDOW: int
    SERVICE_REQUEST_TIMEOUT: float

    BRAIN_API_BASE: str
    BRAIN_MODEL_UID: str
    BRAIN_CONTEXT_WINDOW: int
    BRAIN_REQUEST_TIMEOUT: float

    TRANSLATOR_API_BASE: str
    TRANSLATOR_MODEL_UID: str
    TRANSLATOR_CONTEXT_WINDOW: int
    TRANSLATOR_REQUEST_TIMEOUT: float

    TRANSLATION_MIN_TOKENS: int
    TRANSLATION_MAX_TOKENS: int

    SEARCH_PROVIDER: str
    SEARCH_SERPER_API_KEY: str
    SEARCH_MAX_RESULTS: int
    SEARCH_TIMEOUT: float


settings = AppSettings(

    CHAT_ENDPOINT=config.CHAT_ENDPOINT,

    USE_SERVICE_AS_BRAIN=config.USE_SERVICE_AS_BRAIN,

    SERVICE_API_BASE=config.SERVICE_API_BASE,
    SERVICE_MODEL_UID=config.SERVICE_MODEL_UID,
    SERVICE_CONTEXT_WINDOW=config.SERVICE_CONTEXT_WINDOW,
    SERVICE_REQUEST_TIMEOUT=config.SERVICE_REQUEST_TIMEOUT,

    BRAIN_API_BASE=config.BRAIN_API_BASE,
    BRAIN_MODEL_UID=config.BRAIN_MODEL_UID,
    BRAIN_CONTEXT_WINDOW=config.BRAIN_CONTEXT_WINDOW,
    BRAIN_REQUEST_TIMEOUT=config.BRAIN_REQUEST_TIMEOUT,

    TRANSLATOR_API_BASE=config.TRANSLATOR_API_BASE,
    TRANSLATOR_MODEL_UID=config.TRANSLATOR_MODEL_UID,
    TRANSLATOR_CONTEXT_WINDOW=config.TRANSLATOR_CONTEXT_WINDOW,
    TRANSLATOR_REQUEST_TIMEOUT=config.TRANSLATOR_REQUEST_TIMEOUT,

    TRANSLATION_MIN_TOKENS=config.TRANSLATION_MIN_TOKENS,
    TRANSLATION_MAX_TOKENS=config.TRANSLATION_MAX_TOKENS,

    SEARCH_PROVIDER=getattr(
        config,
        "SEARCH_PROVIDER",
        "serper",
    ),
    SEARCH_SERPER_API_KEY=getattr(
        config,
        "SEARCH_SERPER_API_KEY",
        "",
    ),
    SEARCH_MAX_RESULTS=getattr(
        config,
        "SEARCH_MAX_RESULTS",
        5,
    ),
    SEARCH_TIMEOUT=getattr(
        config,
        "SEARCH_TIMEOUT",
        20.0,
    ),
)
