# Copy this file to config.py and adjust values for your local nodes.
USE_SERVICE_AS_BRAIN = True
BYPASS_BRAIN = False

SERVICE_API_BASE = "http://service-host:1234"
BRAIN_API_BASE = "http://brain-host:1234"

CHAT_ENDPOINT = "/v1/chat/completions"
MODELS_ENDPOINT = "/v1/models"

SERVICE_MODEL_UID = "service-model"
BRAIN_MODEL_UID = "brain_model"

BRAIN_REQUEST_TIMEOUT = 90.0
SERVICE_REQUEST_TIMEOUT = 30.0

BRAIN_MAX_TOKENS = 2048
SERVICE_MAX_TOKENS = 1024

BRAIN_CONTEXT_WINDOW = 32768
SERVICE_CONTEXT_WINDOW = 8192

BRAIN_TEMPERATURE = 0.7
SERVICE_TEMPERATURE = 0.15

TRANSLATION_TIMEOUT = 30.0
TRANSLATION_MAX_TOKENS = 512

TRANSLATION_TEMPERATURE = 0.1
TRANSLATION_RETRIES = 1

TOKEN_ESTIMATION_DIVISOR = 4
