# Internal configuration for built-in document and Python skills.

DOCUMENT_READER_MAX_ITERATIONS = 128
DOCUMENT_READER_MIN_CHUNK_TOKENS = 256
DOCUMENT_READER_MAX_CHUNK_TOKENS = 0
DOCUMENT_READER_RESULT_MAX_TOKENS = 0
DOCUMENT_READER_TEMPERATURE = 0.1
DOCUMENT_READER_SCRIPT_TIMEOUT_SECONDS = 120
DOCUMENT_READER_MODEL_TIMEOUT_SECONDS = 1000.0
DOCUMENT_READER_PROGRESS_HEARTBEAT_SECONDS = 1.0
DOCUMENT_READER_INVALID_OUTPUT_RETRIES = 2

PYTHON_SKILL_TIMEOUT_SECONDS = 120
PYTHON_SKILL_OUTPUT_MAX_CHARS = 60000
