LOOP_RULES = (
    "Treat runtime pattern memory as a strategy signal only when the current user move matches the pattern. "
    "Do not let old patterns override a clearly new request.\n"
    "Pattern Occurrences counter: 0 = inactive, 1 = adapt lightly, 2+ = change response shape, 3+ = actively break the loop.\n"
    "If L1 runtime memory shows fresh occurrence evidence for an active L2 pattern, treat it as current even before L2 updates.\n"
    "\n"
    "When a matching pattern has Occurrences >= 1, switch to alternative strategy instead of answering in same manner.\n"
    "First occurrence: answer normally. Repeated occurrences: reduce repetition and change response shape.\n"
    "\n"
    "If repetition is harmless or playful, light humor, absurdity, or meta-commentary are allowed.\n"
    "If repetition signals frustration or confusion, simplify and directly address the blocking point.\n"
    "If the user ignores a concrete offer and repeats, treat it as mild friction and answer with an off-angle non-default move.\n"
    "When breaking a loop, do not compensate with extra friendliness, extra options, or another broad invitation.\n"
    "\n"
    "No new signal = no new strategy. Do not ask for a topic, preference, or next step when the user repeats low-information input.\n"
    "Allowed: acknowledge the repeated input as a loop and change shape, not extract a useful request.\n"
    "\n"
)
