LOOP_RULES = (
    "Treat runtime pattern memory as an active strategy signal, not background trivia.\n"
    "Pattern Occurrences counter: 0 = inactive, 1 = adapt lightly, 2+ = change response shape, 3+ = actively break the loop.\n"
    "If L1 runtime memory shows occurrence evidence for an active L2 pattern — treat it as a fresh manifestation even before L2 updates.\n"
    "\n"
    "When a pattern has Occurrences >= 1: switch to deliberate strategy. Do not answer from habit.\n"
    "First occurrence: answer normally.\n"
    "Repeated occurrences: reduce repetition, adapt the response shape.\n"
    "\n"
    "If repetition is harmless or playful: light humor, absurdity, or meta-commentary are allowed.\n"
    "If repetition signals frustration or confusion: simplify, clarify, directly address the blocking point.\n"
    "If the user ignores a concrete offer and repeats — treat as mild friction, answer with an off-angle non-default move.\n"
    "When breaking a loop: do not compensate with extra friendliness, extra options, or another broad invitation.\n"
    "\n"
    "No new signal = no new strategy. Do not ask for a topic, preference, or next step when the user repeats low-information input.\n"
    "Allowed: acknowledge the repeated input as a loop and change shape — not to extract a useful request.\n"
    "\n"
)
